/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import javax.swing.*;
import java.util.*;

import controllers.Controller;

/**
 *
 * @author mac
 */
public class AppWindow extends javax.swing.JFrame 
{

    /**
     * Creates new form AppWindow
     */
    private Controller Controller;
    
    private String ProjectID = "";
    private String FeatureID = "";

    public AppWindow() 
    {
        Controller = new Controller();
        initComponents();
        this.setVisible(true);
        AuthPanel.setVisible(true);
        AdminPanel.setVisible(false);
        ProjectsPanel.setVisible(false);
        FeaturesPanel.setVisible(false);
        IssuesPanel.setVisible(false);
        ReportsPanel.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectAddDialog = new javax.swing.JDialog();
        projectNameText = new javax.swing.JTextField();
        projectNameLabel = new javax.swing.JLabel();
        projectDescriptionLabel = new javax.swing.JLabel();
        projectCommentsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectDescriptionText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectCommentsText = new javax.swing.JTextArea();
        projectAddDialogButton = new javax.swing.JButton();
        projectCancelDialogButton = new javax.swing.JButton();
        projectDeleteDialog = new javax.swing.JDialog();
        projectDeleteDialogButton = new javax.swing.JButton();
        projectDeleteCancelDialogButton = new javax.swing.JButton();
        projectDeleteScrollpane = new javax.swing.JScrollPane();
        projectDeleteJList = new javax.swing.JList<>();
        featuresAddDialog = new javax.swing.JDialog();
        featuresNameText = new javax.swing.JTextField();
        featuresNameLabel = new javax.swing.JLabel();
        featuresDescriptionLabel = new javax.swing.JLabel();
        featuresCommentsLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        featuresDescriptionText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        featuresCommentsText = new javax.swing.JTextArea();
        featuresAddDialogButton = new javax.swing.JButton();
        featuresCancelDialogButton = new javax.swing.JButton();
        featuresDeleteDialog = new javax.swing.JDialog();
        featuresDeleteDialogButton = new javax.swing.JButton();
        featuresDeleteCancelDialogButton = new javax.swing.JButton();
        featuresDeleteScrollpane = new javax.swing.JScrollPane();
        featuresDeleteJList = new javax.swing.JList<>();
        AuthPanel = new javax.swing.JPanel();
        authPasswordLabell = new javax.swing.JLabel();
        authPasswordField = new javax.swing.JPasswordField();
        authSubmitButton = new javax.swing.JButton();
        authCancelButton = new javax.swing.JButton();
        authLoginLabel = new javax.swing.JLabel();
        authUsernameLabel = new javax.swing.JLabel();
        authUsernameField = new javax.swing.JTextField();
        authLoginStatusLabel = new javax.swing.JLabel();
        ProjectsPanel = new javax.swing.JPanel();
        projectAdminButton = new javax.swing.JButton();
        projectLogoutButton = new javax.swing.JButton();
        projectRefreshButton = new javax.swing.JButton();
        projectReportButton = new javax.swing.JButton();
        projectAddButton = new javax.swing.JButton();
        projectUpdateButton = new javax.swing.JButton();
        projectDeleteButton = new javax.swing.JButton();
        projectScrollPane = new javax.swing.JScrollPane();
        AdminPanel = new javax.swing.JPanel();
        IssuesPanel = new javax.swing.JPanel();
        ReportsPanel = new javax.swing.JPanel();
        FeaturesPanel = new javax.swing.JPanel();
        featuresAdminButton = new javax.swing.JButton();
        featuresLogoutButton = new javax.swing.JButton();
        featuresRefreshButton = new javax.swing.JButton();
        featuresReportButton = new javax.swing.JButton();
        featuresAddButton = new javax.swing.JButton();
        featuresUpdateButton = new javax.swing.JButton();
        featuresDeleteButton = new javax.swing.JButton();
        featuresScrollPane = new javax.swing.JScrollPane();
        featuresProjectButton = new javax.swing.JButton();

        projectNameText.setText("Project Name");

        projectNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectNameLabel.setText("Project Name");

        projectDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectDescriptionLabel.setText("Project Description");

        projectCommentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectCommentsLabel.setText("Project Comments");

        projectDescriptionText.setColumns(20);
        projectDescriptionText.setRows(5);
        jScrollPane1.setViewportView(projectDescriptionText);

        projectCommentsText.setColumns(20);
        projectCommentsText.setRows(5);
        jScrollPane2.setViewportView(projectCommentsText);

        projectAddDialogButton.setText("Add");
        projectAddDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectAddDialogButtonActionPerformed(evt);
            }
        });

        projectCancelDialogButton.setText("Cancel");
        projectCancelDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectCancelDialogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout projectAddDialogLayout = new javax.swing.GroupLayout(projectAddDialog.getContentPane());
        projectAddDialog.getContentPane().setLayout(projectAddDialogLayout);
        projectAddDialogLayout.setHorizontalGroup(
            projectAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectAddDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(projectAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectNameLabel)
                    .addComponent(projectDescriptionLabel)
                    .addComponent(projectCommentsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(projectAddDialogLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(projectAddDialogButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(projectCancelDialogButton)
                .addGap(57, 57, 57))
        );

        projectAddDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {projectCommentsLabel, projectDescriptionLabel, projectNameLabel});

        projectAddDialogLayout.setVerticalGroup(
            projectAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectAddDialogLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(projectNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(projectDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(projectCommentsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(projectAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectAddDialogButton)
                    .addComponent(projectCancelDialogButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        projectDeleteDialog.setPreferredSize(new java.awt.Dimension(440, 400));
        projectDeleteDialog.setSize(new java.awt.Dimension(440, 400));

        projectDeleteDialogButton.setText("Delete");
        projectDeleteDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectDeleteDialogButtonActionPerformed(evt);
            }
        });

        projectDeleteCancelDialogButton.setText("Cancel");
        projectDeleteCancelDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectDeleteCancelDialogButtonActionPerformed(evt);
            }
        });

        projectDeleteJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        projectDeleteScrollpane.setViewportView(projectDeleteJList);

        javax.swing.GroupLayout projectDeleteDialogLayout = new javax.swing.GroupLayout(projectDeleteDialog.getContentPane());
        projectDeleteDialog.getContentPane().setLayout(projectDeleteDialogLayout);
        projectDeleteDialogLayout.setHorizontalGroup(
            projectDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectDeleteDialogLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(projectDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(projectDeleteScrollpane)
                    .addGroup(projectDeleteDialogLayout.createSequentialGroup()
                        .addComponent(projectDeleteDialogButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(projectDeleteCancelDialogButton)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        projectDeleteDialogLayout.setVerticalGroup(
            projectDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectDeleteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectDeleteScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projectDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectDeleteDialogButton)
                    .addComponent(projectDeleteCancelDialogButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        featuresNameText.setText("Feature Name");

        featuresNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        featuresNameLabel.setText("Feature Name");

        featuresDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        featuresDescriptionLabel.setText("Feature Description");

        featuresCommentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        featuresCommentsLabel.setText("Feature Comments");

        featuresDescriptionText.setColumns(20);
        featuresDescriptionText.setRows(5);
        jScrollPane3.setViewportView(featuresDescriptionText);

        featuresCommentsText.setColumns(20);
        featuresCommentsText.setRows(5);
        jScrollPane4.setViewportView(featuresCommentsText);

        featuresAddDialogButton.setText("Add");
        featuresAddDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featuresAddDialogButtonActionPerformed(evt);
            }
        });

        featuresCancelDialogButton.setText("Cancel");
        featuresCancelDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featuresCancelDialogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout featuresAddDialogLayout = new javax.swing.GroupLayout(featuresAddDialog.getContentPane());
        featuresAddDialog.getContentPane().setLayout(featuresAddDialogLayout);
        featuresAddDialogLayout.setHorizontalGroup(
            featuresAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(featuresAddDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(featuresAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(featuresNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(featuresNameLabel)
                    .addComponent(featuresDescriptionLabel)
                    .addComponent(featuresCommentsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(featuresAddDialogLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(featuresAddDialogButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(featuresCancelDialogButton)
                .addGap(57, 57, 57))
        );
        featuresAddDialogLayout.setVerticalGroup(
            featuresAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(featuresAddDialogLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(featuresNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(featuresNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(featuresDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(featuresCommentsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(featuresAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(featuresAddDialogButton)
                    .addComponent(featuresCancelDialogButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        featuresDeleteDialog.setPreferredSize(new java.awt.Dimension(440, 400));
        featuresDeleteDialog.setSize(new java.awt.Dimension(440, 400));

        featuresDeleteDialogButton.setText("Delete");
        featuresDeleteDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featuresDeleteDialogButtonActionPerformed(evt);
            }
        });

        featuresDeleteCancelDialogButton.setText("Cancel");
        featuresDeleteCancelDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featuresDeleteCancelDialogButtonActionPerformed(evt);
            }
        });

        featuresDeleteJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        featuresDeleteScrollpane.setViewportView(featuresDeleteJList);

        javax.swing.GroupLayout featuresDeleteDialogLayout = new javax.swing.GroupLayout(featuresDeleteDialog.getContentPane());
        featuresDeleteDialog.getContentPane().setLayout(featuresDeleteDialogLayout);
        featuresDeleteDialogLayout.setHorizontalGroup(
            featuresDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, featuresDeleteDialogLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(featuresDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(featuresDeleteScrollpane)
                    .addGroup(featuresDeleteDialogLayout.createSequentialGroup()
                        .addComponent(featuresDeleteDialogButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(featuresDeleteCancelDialogButton)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        featuresDeleteDialogLayout.setVerticalGroup(
            featuresDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, featuresDeleteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(featuresDeleteScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(featuresDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(featuresDeleteDialogButton)
                    .addComponent(featuresDeleteCancelDialogButton))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Issue Tracker");
        setName("Issue Tracker Frame"); // NOI18N
        getContentPane().setLayout(new java.awt.CardLayout());

        AuthPanel.setPreferredSize(new java.awt.Dimension(500, 400));

        authPasswordLabell.setText("Password");

        authPasswordField.setPreferredSize(new java.awt.Dimension(130, 26));
        authPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                authPasswordFieldKeyPressed(evt);
            }
        });

        authSubmitButton.setText("Submit");
        authSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authSubmitButtonActionPerformed(evt);
            }
        });

        authCancelButton.setText("Cancel");
        authCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authCancelButtonActionPerformed(evt);
            }
        });

        authLoginLabel.setText("Login");

        authUsernameLabel.setText("Username");

        authUsernameField.setText("Username");
        authUsernameField.setPreferredSize(new java.awt.Dimension(130, 26));

        javax.swing.GroupLayout AuthPanelLayout = new javax.swing.GroupLayout(AuthPanel);
        AuthPanel.setLayout(AuthPanelLayout);
        AuthPanelLayout.setHorizontalGroup(
            AuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthPanelLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(AuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(authLoginLabel)
                    .addComponent(authUsernameLabel)
                    .addComponent(authUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authPasswordLabell)
                    .addComponent(authPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AuthPanelLayout.createSequentialGroup()
                        .addComponent(authSubmitButton)
                        .addGap(66, 66, 66)
                        .addComponent(authCancelButton))
                    .addComponent(authLoginStatusLabel))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        AuthPanelLayout.setVerticalGroup(
            AuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(authLoginLabel)
                .addGap(18, 18, 18)
                .addComponent(authUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(authPasswordLabell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authSubmitButton)
                    .addComponent(authCancelButton))
                .addGap(18, 18, 18)
                .addComponent(authLoginStatusLabel)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        getContentPane().add(AuthPanel, "card0");

        ProjectsPanel.setMinimumSize(new java.awt.Dimension(500, 400));
        ProjectsPanel.setPreferredSize(new java.awt.Dimension(500, 400));

        projectAdminButton.setText("Admininstration");

        projectLogoutButton.setText("Logout");
        projectLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectLogoutButtonActionPerformed(evt);
            }
        });

        projectRefreshButton.setText("Refresh");
        projectRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectRefreshButtonActionPerformed(evt);
            }
        });

        projectReportButton.setText("Report Generator");
        projectReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectReportButtonActionPerformed(evt);
            }
        });

        projectAddButton.setText("Add Project");
        projectAddButton.setMaximumSize(new java.awt.Dimension(146, 29));
        projectAddButton.setMinimumSize(new java.awt.Dimension(146, 29));
        projectAddButton.setPreferredSize(new java.awt.Dimension(146, 29));
        projectAddButton.setSize(new java.awt.Dimension(146, 29));
        projectAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectAddButtonActionPerformed(evt);
            }
        });

        projectUpdateButton.setText("Update Project");
        projectUpdateButton.setMaximumSize(new java.awt.Dimension(146, 29));
        projectUpdateButton.setMinimumSize(new java.awt.Dimension(146, 29));

        projectDeleteButton.setText("Delete Project");
        projectDeleteButton.setMaximumSize(new java.awt.Dimension(146, 29));
        projectDeleteButton.setMinimumSize(new java.awt.Dimension(146, 29));
        projectDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProjectsPanelLayout = new javax.swing.GroupLayout(ProjectsPanel);
        ProjectsPanel.setLayout(ProjectsPanelLayout);
        ProjectsPanelLayout.setHorizontalGroup(
            ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectReportButton)
                    .addComponent(projectAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectLogoutButton)
                    .addComponent(projectAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectsPanelLayout.createSequentialGroup()
                        .addComponent(projectRefreshButton)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectsPanelLayout.createSequentialGroup()
                        .addComponent(projectScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        ProjectsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {projectAddButton, projectAdminButton, projectDeleteButton, projectReportButton, projectUpdateButton});

        ProjectsPanelLayout.setVerticalGroup(
            ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectsPanelLayout.createSequentialGroup()
                .addGroup(ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProjectsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(projectReportButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projectAdminButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projectAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projectUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projectDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(projectScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)))
                .addGroup(ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectLogoutButton)
                    .addComponent(projectRefreshButton))
                .addContainerGap())
        );

        getContentPane().add(ProjectsPanel, "card3");

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        getContentPane().add(AdminPanel, "card4");

        javax.swing.GroupLayout IssuesPanelLayout = new javax.swing.GroupLayout(IssuesPanel);
        IssuesPanel.setLayout(IssuesPanelLayout);
        IssuesPanelLayout.setHorizontalGroup(
            IssuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        IssuesPanelLayout.setVerticalGroup(
            IssuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        getContentPane().add(IssuesPanel, "card6");

        javax.swing.GroupLayout ReportsPanelLayout = new javax.swing.GroupLayout(ReportsPanel);
        ReportsPanel.setLayout(ReportsPanelLayout);
        ReportsPanelLayout.setHorizontalGroup(
            ReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        ReportsPanelLayout.setVerticalGroup(
            ReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        getContentPane().add(ReportsPanel, "card7");

        FeaturesPanel.setMinimumSize(new java.awt.Dimension(500, 400));

        featuresAdminButton.setText("Admininstration");

        featuresLogoutButton.setText("Logout");
        featuresLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featuresLogoutButtonActionPerformed(evt);
            }
        });

        featuresRefreshButton.setText("Refresh");
        featuresRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featuresRefreshButtonActionPerformed(evt);
            }
        });

        featuresReportButton.setText("Report Generator");
        featuresReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featuresReportButtonActionPerformed(evt);
            }
        });

        featuresAddButton.setText("Add Feature");
        featuresAddButton.setMaximumSize(new java.awt.Dimension(146, 29));
        featuresAddButton.setMinimumSize(new java.awt.Dimension(146, 29));
        featuresAddButton.setPreferredSize(new java.awt.Dimension(146, 29));
        featuresAddButton.setSize(new java.awt.Dimension(146, 29));
        featuresAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featuresAddButtonActionPerformed(evt);
            }
        });

        featuresUpdateButton.setText("Update Feature");
        featuresUpdateButton.setMaximumSize(new java.awt.Dimension(146, 29));
        featuresUpdateButton.setMinimumSize(new java.awt.Dimension(146, 29));

        featuresDeleteButton.setText("Delete Feature");
        featuresDeleteButton.setMaximumSize(new java.awt.Dimension(146, 29));
        featuresDeleteButton.setMinimumSize(new java.awt.Dimension(146, 29));
        featuresDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featuresDeleteButtonActionPerformed(evt);
            }
        });

        featuresProjectButton.setText("Projects");
        featuresProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featuresProjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FeaturesPanelLayout = new javax.swing.GroupLayout(FeaturesPanel);
        FeaturesPanel.setLayout(FeaturesPanelLayout);
        FeaturesPanelLayout.setHorizontalGroup(
            FeaturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FeaturesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FeaturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(featuresProjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(featuresDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(featuresUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(featuresAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(featuresAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(featuresReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(FeaturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FeaturesPanelLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(featuresRefreshButton))
                    .addGroup(FeaturesPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(featuresScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(FeaturesPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(featuresLogoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FeaturesPanelLayout.setVerticalGroup(
            FeaturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeaturesPanelLayout.createSequentialGroup()
                .addGroup(FeaturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FeaturesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(featuresReportButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(featuresAdminButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(featuresAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(featuresUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(featuresDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(featuresProjectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FeaturesPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(featuresScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)))
                .addGroup(FeaturesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(featuresLogoutButton)
                    .addComponent(featuresRefreshButton))
                .addContainerGap())
        );

        getContentPane().add(FeaturesPanel, "card3");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void authCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authCancelButtonActionPerformed
        // TODO add your handling code here:
        if(Controller.getToken()!=null)
        {
            Logout();
        }
        System.exit(0);
    }//GEN-LAST:event_authCancelButtonActionPerformed

    private void authSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authSubmitButtonActionPerformed
        // TODO add your handling code here:
        Login();
    }//GEN-LAST:event_authSubmitButtonActionPerformed

    private void projectLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectLogoutButtonActionPerformed
        // TODO add your handling code here:
        ProjectsPanel.setVisible(false);
        Logout();
    }//GEN-LAST:event_projectLogoutButtonActionPerformed

    private void projectReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectReportButtonActionPerformed
        // TODO add your handling code here:
        ProjectsPanel.setVisible(false);
        ReportsPanel.setVisible(true);
    }//GEN-LAST:event_projectReportButtonActionPerformed

    private void projectRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectRefreshButtonActionPerformed
        // TODO add your handling code here:
        ProjectRefresh();
    }//GEN-LAST:event_projectRefreshButtonActionPerformed

    private void projectAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectAddButtonActionPerformed
        // TODO add your handling code here:
        projectAddDialog.setSize(440,400);
        projectAddDialog.setLocationRelativeTo(null);
        projectCommentsText.setText("");
        projectDescriptionText.setText("");
        projectNameText.setText("Project Name");
        projectAddDialog.setVisible(true);
    }//GEN-LAST:event_projectAddButtonActionPerformed

    private void projectDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectDeleteButtonActionPerformed
        // TODO add your handling code here:
        projectDeleteDialog.setSize(440,400);
        projectDeleteDialog.setLocationRelativeTo(null);
        ProjectDeleteRefresh();
        projectDeleteDialog.setVisible(true);
    }//GEN-LAST:event_projectDeleteButtonActionPerformed

    private void projectAddDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectAddDialogButtonActionPerformed
        // TODO add your handling code here:
        String response;
        response = Controller.projects.addProject(projectNameText.getText(), projectDescriptionText.getText(),projectCommentsText.getText());
        System.out.println(response);
        ProjectRefresh();
        projectAddDialog.setVisible(false);
        projectCommentsText.setText("");
        projectDescriptionText.setText("");
        projectNameText.setText("Project Name");
    }//GEN-LAST:event_projectAddDialogButtonActionPerformed

    private void projectCancelDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectCancelDialogButtonActionPerformed
        // TODO add your handling code here:
        projectAddDialog.setVisible(false);
        projectCommentsText.setText("");
        projectDescriptionText.setText("");
        projectNameText.setText("Project Name");
    }//GEN-LAST:event_projectCancelDialogButtonActionPerformed

    private void projectDeleteCancelDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectDeleteCancelDialogButtonActionPerformed
        // TODO add your handling code here:
        ProjectRefresh();
        projectDeleteDialog.setVisible(false);
    }//GEN-LAST:event_projectDeleteCancelDialogButtonActionPerformed

    private void projectDeleteDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectDeleteDialogButtonActionPerformed
        // TODO add your handling code here:
        int indexes[];
        Vector names = new Vector(0,0);
        Vector projectIDs = new Vector(0,0);
        String response;
        String temp[];
        
        indexes = projectDeleteJList.getSelectedIndices();
        
        response = Controller.projects.getAllProject();
       
        response = response.replaceAll(":", "");
        
        temp = response.split("\"");
        
        for (int i = 0 ; i < temp.length ; i++)
        {
            if(temp[i].matches("name"))
            {
                projectIDs.addElement(new String(temp[i+6]));
            }
        }
        
        for(int i = 0; i < indexes.length; i++)
        {
            response = Controller.projects.deleteProject((String) projectIDs.get(indexes[i]));
            System.out.println(response);
        }
        
        ProjectDeleteRefresh();
    }//GEN-LAST:event_projectDeleteDialogButtonActionPerformed

    private void authPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authPasswordFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
          Login();
        }
    }//GEN-LAST:event_authPasswordFieldKeyPressed

    private void featuresLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featuresLogoutButtonActionPerformed
        // TODO add your handling code here:
        Logout();
    }//GEN-LAST:event_featuresLogoutButtonActionPerformed

    private void featuresRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featuresRefreshButtonActionPerformed
        // TODO add your handling code here:
        FeatureRefresh();
    }//GEN-LAST:event_featuresRefreshButtonActionPerformed

    private void featuresReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featuresReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_featuresReportButtonActionPerformed

    private void featuresAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featuresAddButtonActionPerformed
        // TODO add your handling code here:
        featuresAddDialog.setSize(440,400);
        featuresAddDialog.setLocationRelativeTo(null);
        featuresCommentsText.setText("");
        featuresDescriptionText.setText("");
        featuresNameText.setText("Features Name");
        featuresAddDialog.setVisible(true);
    }//GEN-LAST:event_featuresAddButtonActionPerformed

    private void featuresDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featuresDeleteButtonActionPerformed
        // TODO add your handling code here:
        featuresDeleteDialog.setSize(440,400);
        featuresDeleteDialog.setLocationRelativeTo(null);
        FeatureDeleteRefresh();
        featuresDeleteDialog.setVisible(true);
    }//GEN-LAST:event_featuresDeleteButtonActionPerformed

    private void featuresAddDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featuresAddDialogButtonActionPerformed
        // TODO add your handling code here:
        String response;
        response = Controller.features.addFeature(featuresNameText.getText(), featuresDescriptionText.getText(),featuresCommentsText.getText(), ProjectID);
        System.out.println(response);
        FeatureRefresh();
        featuresAddDialog.setVisible(false);
        featuresCommentsText.setText("");
        featuresDescriptionText.setText("");
        featuresNameText.setText("Features Name");
    }//GEN-LAST:event_featuresAddDialogButtonActionPerformed

    private void featuresCancelDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featuresCancelDialogButtonActionPerformed
        // TODO add your handling code here:
        featuresAddDialog.setVisible(false);
        featuresCommentsText.setText("");
        featuresDescriptionText.setText("");
        featuresNameText.setText("Features Name");
    }//GEN-LAST:event_featuresCancelDialogButtonActionPerformed

    private void featuresDeleteDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featuresDeleteDialogButtonActionPerformed
        // TODO add your handling code here:
        int indexes[];
        Vector names = new Vector(0,0);
        Vector featuresIDs = new Vector(0,0);
        String response;
        String temp[];
        
        indexes = featuresDeleteJList.getSelectedIndices();
        
        response = Controller.features.getProjectFeatures(ProjectID);
        
        temp = response.split("\"");
        
        for (int i = 0 ; i < temp.length ; i++)
        {
            if(temp[i].matches("name"))
            {
                featuresIDs.addElement(new String(temp[i+6]));
            }
        }
        
        for(int i = 0; i < indexes.length; i++)
        {
            response = Controller.features.deleteFeature((String) featuresIDs.get(indexes[i]));
            System.out.println(response);
        }
        
        FeatureDeleteRefresh();
    }//GEN-LAST:event_featuresDeleteDialogButtonActionPerformed

    private void featuresDeleteCancelDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featuresDeleteCancelDialogButtonActionPerformed
        // TODO add your handling code here:
        FeatureRefresh();
        featuresDeleteDialog.setVisible(false);
    }//GEN-LAST:event_featuresDeleteCancelDialogButtonActionPerformed

    private void featuresProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featuresProjectButtonActionPerformed
        // TODO add your handling code here:
        ProjectRefresh();
        ProjectsPanel.setVisible(true);
        FeaturesPanel.setVisible(false);
    }//GEN-LAST:event_featuresProjectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new AppWindow().setVisible(true);
            }
        });
    }
    
    private void Login()
    {
        String username = authUsernameField.getText();
        String password = new String(authPasswordField.getPassword());
        boolean valid = false;

        //Clear Password
        authPasswordField.setText("");

        try 
        {
            valid = Controller.auth.login(username, password);
            
        }
        
        catch (Exception ex) 
        {
            Logger.getLogger(AppWindow.class.getName()).log(Level.SEVERE, null, ex);
            valid = false;
        }

        if (valid) 
        {
            ProjectRefresh();

            AuthPanel.setVisible(false);
            ProjectsPanel.setVisible(true);

            authLoginStatusLabel.setText("");
        } 
        
        else 
        {
            authLoginStatusLabel.setText("Invalid Username/Password!");
        }
    }

    private void Logout() 
    {
        if (Controller.auth.logout()) 
        {
            authLoginStatusLabel.setText("Logout Successful");
        } 
        else 
        {
            authLoginStatusLabel.setText("Invalid Session Token");
        }

        AuthPanel.setVisible(true);
    }

    private void ProjectRefresh() 
    {
        String response = Controller.projects.getAllProject();
        
        Vector names = new Vector(0,0);
        final Vector projectIDs = new Vector(0,0);
        Vector descriptions = new Vector(0,0);
        Vector comments = new Vector(0,0);

        String temp[];
       
        response = response.replaceAll(":", "");
        
        temp = response.split("\"");
        
        for (int i = 0 ; i < temp.length ; i++)
        {
            if(temp[i].matches("name"))
            {
                names.addElement(new String(temp[i+2]));
            }
            if(temp[i].matches("comment"))
            {
                comments.addElement(new String(temp[i+2]));
            }
            if(temp[i].matches("description"))
            {
                descriptions.addElement(new String(temp[i+2]));
            }
            if(temp[i].matches("objectId"))
            {
                projectIDs.addElement(new String(temp[i+2]));
            }
        }
        
        JPanel buffer; //only 1, please
        
//create stuff to put in the scroll pane
        buffer = new JPanel(new GridLayout(0, 1, 0, 4));

        for (int i = 0; i < names.size() ; i++) 
        {
            JPanel subbuffer = new JPanel(new GridLayout(3, 1)); //lots of these

            final int x = i;
            JButton projectbutton = new JButton((String)names.get(x));
            
            projectbutton.addActionListener(new java.awt.event.ActionListener() 
            {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {
                String response;
                ProjectID = (String)projectIDs.get(x);
                FeatureRefresh();
                FeaturesPanel.setVisible(true);
                ProjectsPanel.setVisible(false);
            }
            });

            JLabel text0 = new JLabel((String)descriptions.get(i));

            JLabel text1 = new JLabel((String)comments.get(i));

            subbuffer.add(projectbutton);

            subbuffer.add(text0);

            subbuffer.add(text1);
            
            buffer.add(subbuffer);

        }
        
        projectScrollPane.add(buffer);
        projectScrollPane.setViewportView(buffer);
    }
    
    private void FeatureRefresh() 
    {
        String response = Controller.features.getProjectFeatures(ProjectID);
        
        Vector names = new Vector(0,0);
        Vector featureIDs = new Vector(0,0);
        Vector descriptions = new Vector(0,0);

        String temp[];
        
        temp = response.split("\"");
        
        for (int i = 0 ; i < temp.length ; i++)
        { 
            if(temp[i].matches("name"))
            {
                names.addElement(new String(temp[i+2]));
            }
            if(temp[i].matches("description"))
            {
                descriptions.addElement(new String(temp[i+2]));
            }
            if(temp[i].matches("objectId"))
            {
                if(!temp[i+2].equals(ProjectID))
                {
                    featureIDs.addElement(new String(temp[i+2]));
                }
            }
        }
        
        JPanel buffer; //only 1, please
        
//create stuff to put in the scroll pane
        buffer = new JPanel(new GridLayout(0, 1, 0, 4));

        for (int i = 0; i < names.size() ; i++) 
        {
            JPanel subbuffer = new JPanel(new GridLayout(3, 1)); //lots of these

            JButton button = new JButton((String)names.get(i));

            JLabel text0 = new JLabel((String)descriptions.get(i));

            subbuffer.add(button);

            subbuffer.add(text0);
            
            buffer.add(subbuffer);

        }
        
        featuresScrollPane.add(buffer);
        featuresScrollPane.setViewportView(buffer);
    }
    
    private void FeatureDeleteRefresh()
    {
        String response = Controller.features.getProjectFeatures(ProjectID);
        
        Vector names = new Vector(0,0);
        
        Vector featureIDs = new Vector(0,0);
        
        String temp[];
        
        response = response.replaceAll(":", "");
        
        temp = response.split("\"");
        
        for (int i = 0 ; i < temp.length ; i++)
        { 
            if(temp[i].matches("name"))
            {
                names.addElement(new String(temp[i+2]));
            }
            if(temp[i].matches("objectId"))
            {
                if(!temp[i+2].equals(ProjectID))
                {
                    featureIDs.addElement(new String(temp[i+2]));
                }
            }
        }
        
        featuresDeleteJList = new JList(names);
        featuresDeleteScrollpane.setViewportView(featuresDeleteJList); 
    }

    private void ProjectDeleteRefresh()
    {
        String response;
        
        response = Controller.projects.getAllProject();
        
        Vector names = new Vector(0,0);
        
        Vector projectIDs = new Vector(0,0);
        
        String temp[];
        
        response = response.replaceAll(":", "");
        
        temp = response.split("\"");
        
        for (int i = 0 ; i < temp.length ; i++)
        {
            if(temp[i].matches("name"))
            {
                names.addElement(new String (temp[i+2]));
                projectIDs.addElement(new String(temp[i+6]));
            }
        }
        
        projectDeleteJList = new JList(names);
        projectDeleteScrollpane.setViewportView(projectDeleteJList);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel AuthPanel;
    private javax.swing.JPanel FeaturesPanel;
    private javax.swing.JPanel IssuesPanel;
    private javax.swing.JPanel ProjectsPanel;
    private javax.swing.JPanel ReportsPanel;
    private javax.swing.JButton authCancelButton;
    private javax.swing.JLabel authLoginLabel;
    private javax.swing.JLabel authLoginStatusLabel;
    private javax.swing.JPasswordField authPasswordField;
    private javax.swing.JLabel authPasswordLabell;
    private javax.swing.JButton authSubmitButton;
    private javax.swing.JTextField authUsernameField;
    private javax.swing.JLabel authUsernameLabel;
    private javax.swing.JButton featuresAddButton;
    private javax.swing.JDialog featuresAddDialog;
    private javax.swing.JButton featuresAddDialogButton;
    private javax.swing.JButton featuresAdminButton;
    private javax.swing.JButton featuresCancelDialogButton;
    private javax.swing.JLabel featuresCommentsLabel;
    private javax.swing.JTextArea featuresCommentsText;
    private javax.swing.JButton featuresDeleteButton;
    private javax.swing.JButton featuresDeleteCancelDialogButton;
    private javax.swing.JDialog featuresDeleteDialog;
    private javax.swing.JButton featuresDeleteDialogButton;
    private javax.swing.JList<String> featuresDeleteJList;
    private javax.swing.JScrollPane featuresDeleteScrollpane;
    private javax.swing.JLabel featuresDescriptionLabel;
    private javax.swing.JTextArea featuresDescriptionText;
    private javax.swing.JButton featuresLogoutButton;
    private javax.swing.JLabel featuresNameLabel;
    private javax.swing.JTextField featuresNameText;
    private javax.swing.JButton featuresProjectButton;
    private javax.swing.JButton featuresRefreshButton;
    private javax.swing.JButton featuresReportButton;
    private javax.swing.JScrollPane featuresScrollPane;
    private javax.swing.JButton featuresUpdateButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton projectAddButton;
    private javax.swing.JDialog projectAddDialog;
    private javax.swing.JButton projectAddDialogButton;
    private javax.swing.JButton projectAdminButton;
    private javax.swing.JButton projectCancelDialogButton;
    private javax.swing.JLabel projectCommentsLabel;
    private javax.swing.JTextArea projectCommentsText;
    private javax.swing.JButton projectDeleteButton;
    private javax.swing.JButton projectDeleteCancelDialogButton;
    private javax.swing.JDialog projectDeleteDialog;
    private javax.swing.JButton projectDeleteDialogButton;
    private javax.swing.JList<String> projectDeleteJList;
    private javax.swing.JScrollPane projectDeleteScrollpane;
    private javax.swing.JLabel projectDescriptionLabel;
    private javax.swing.JTextArea projectDescriptionText;
    private javax.swing.JButton projectLogoutButton;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameText;
    private javax.swing.JButton projectRefreshButton;
    private javax.swing.JButton projectReportButton;
    private javax.swing.JScrollPane projectScrollPane;
    private javax.swing.JButton projectUpdateButton;
    // End of variables declaration//GEN-END:variables
}
